### PR TITLE
5.0 dev

### PR DESCRIPTION
**Pull request by JGillam**

### CODE REVIEW

**Review by secureideas — COMMENTED** [review]
Looks good.  Will start a build to test.

**Comment by corysabol** [comment]
I'll kick a build off here in a second. Is there a list of items that need to be checked as working or not?

**Comment by corysabol** [comment]
Actually I'll kick it off in the am.

**Comment by JGillam** [comment]
No, we technically already tested this since it is what we used for the BSides Charlotte workshop last weekend.  Probably just a sanity check that it builds, you can log in, and Katana is running, without significant errors.

**Review by secureideas — APPROVED** [review]

**Pull request merged**
